genny-project/prj_genny

- rules/rulesCurrent/Test/5_Timer.drl
- rules/rulesCurrent/shared/05_Workflows/SELECTIONS_BEG/10_SendApplicationsForSelectedBEG.drl
Please check this genny rule for internmatch.
It has been changed to work for PCSS.
> fix SendApplications For PCSS

- rules/fixrules.sh
- rules/rulesCurrent/shared/05_Workflows/AUTH_INIT/80_VerifyMobileNumber/32_PassCodeVerificationFailed.drl
- rules/rulesCurrent/shared/TO_UPDATE/Profile/UserProfileSubmit.drl
- rules/substitute.sh
To fix the rules that use messaging..
> Added rules fixing scripts

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form1.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form10.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form11.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form12.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form13.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form2.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form3.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form4.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form5.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form6.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form7.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form8.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form9.drl
- src/test/java/life/genny/test/CyrusTest.java
added all the forms in use for the agent to the form generator.
> Form generator

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form1.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form10.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form11.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form12.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form13.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form2.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form3.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form4.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form5.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form6.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form7.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form8.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form9.drl
- src/test/java/life/genny/test/CyrusTest.java
Have added the code so that the form now is being saved to the cache and got rid of unnecessary frames which do not needs to be passed.
> Cyrus form

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form14.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form15.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form16.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form17.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form18.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form19.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form20.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form5.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form6.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form7.drl
- src/test/java/life/genny/test/CyrusTest.java
pull request for host company staff forms
> Host company

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form14.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form15.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateForms/form16.drl
- src/test/java/life/genny/test/CyrusTest.java
Added the forms accessible to Education Provider Staff
> Edu provider

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/GenerateForms/FRM_FORM.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/GenerateForms/FRM_MAIN.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/GenerateForms/FRM_ROOT.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/GenerateForms/XXXFRM_FINAL.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/GenerateForms/XXXFRM_PRE.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateThemes/Colours/THM_OF.drl
- src/test/java/life/genny/test/AnishTest.java
- src/test/java/life/genny/test/CyrusTest.java
This pull request includes all the forms cached into the cache and demo calling them to the testDesktop in AnishTest
> Theme for forms

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/MainFrame/FRM_SIDEBAR.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/Tree/FRM_TREE_BUCKET_VIEW.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/Tree/FRM_TREE_DETAIL_VIEW.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/Tree/FRM_TREE_FORM_VIEW.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/Tree/FRM_TREE_TABLE_VIEW.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateThemes/THM_TREE_ITEM.drl
> Anish tree items

- rules/rulesCurrent/shared/RULEGROUPS/EventProcessing/OptionClickEvent/FORM_CLICK_EVENT.drl
Updated the frame to pass the generic profile rather than realm-specific profile when logged in.
> changed the FRM to display the generic profile detail

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateFrames/GenerateForms/FRM_FORM.drl
This commit contains the changes to show the date properly.
> added theme and visualType to display the date picker correctly

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateThemes/Form/THM_FORM_VCL_WRAPPER_GENNY.drl
- src/test/java/life/genny/test/CyrusTest.java
removed the padding that was coming around the button and added margin to the components
> Button fix

- pom.xml
include Java Faker with pom.xml
> include Java Faker with pom.xml

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/XXX_Lin/ActionCache.bpmn
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/XXX_Lin/ActionCache.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/XXX_Lin/ActionCache.md
- src/test/java/life/genny/test/LinTestActionCache.java
Test case, BPMN, Drools and MD files for action cache
> Test case, BPMN, Drools and MD files for action cache

- src/test/java/life/genny/test/LinTestActionCache.java
Add assertion for the frame toggle test case
> Add assertion for the frame toggle test case

- Jenkinsfile
Yo Chris! can you review and merge this bro?
> Jenkinsfile to build on PR

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateThemes/Bucket/BucketHeader/THM_BH_ROW_TWO_GRP_CONTENT_WRAPPER.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateThemes/Bucket/BucketHeader/THM_BH_ROW_TWO_INPUT_FIELD.drl
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/InitialiseProject/GenerateThemes/Bucket/BucketHeader/THM_BH_ROW_TWO_VCL_WRAPPER.drl
> :recycle: added theme to cache

- rules/rulesCurrent/shared/RULEGROUPS/EventProcessing/TableEvents/START_UNITY_CLICK_EVENT.drl
new file:   rules/rulesCurrent/shared/RULEGROUPS/EventProcessing/TableEvents/START_UNITY_CLICK_EVENT.drl
> added rule for stt

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/Lifecycles/progressJournals.bpmn
- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/Lifecycles/scenario1.bpmn
modified:   rules/rulesCurrent/shared/_BPMN_WORKFLOWS/Lifecycles/progressJournals.bpmn
new file:   rules/rulesCurrent/shared/_BPMN_WORKFLOWS/Lifecycles/scenario1.bpmn
> add loop for stt questions

- rules/rulesCurrent/shared/_BPMN_WORKFLOWS/Lifecycles/INTERNSHIP_S1.bpmn
modified:   rules/rulesCurrent/shared/_BPMN_WORKFLOWS/Lifecycles/INTERNSHIP_S1.bpmn
> add link for internship

- rules/rulesCurrent/shared/RULEGROUPS/EventProcessing/TableEvents/START_UNITY_CLICK_EVENT.drl
modified:   rules/rulesCurrent/shared/RULEGROUPS/EventProcessing/TableEvents/START_UNITY_CLICK_EVENT.drl
> edit rul for firing scenarios

- rules/rulesCurrent/shared/RULEGROUPS/GenerateResources/GenerateThemes/Icon/THM_ICON_ONLY.drl
- Add `PRI_IS_ICON_ONLY` back to the theme `THM_ICON_ONLY`
> Add PRI_IS_ICON_ONLY to the theme back again
